apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nodejs
spec:
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: "gcr.io/zuru-tech-hiring/nodejs:latest"
        imagePullPolicy: Always
        resources:
          requests:
            memory: 100Mi
            cpu: 50m
          limits:
            memory: 1536Mi
            cpu: 55m
        env:
            - name: POSTGRES_HOST
              value: postgres-svc
            - name: POSTGRES_PORT
              value: '5432'
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: root_password
        ports:
        - containerPort: 8080
