apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.global-static-ip-name: nodejs-static-ip
    networking.gke.io/managed-certificates: nodejs-domain-certificate
  labels:
    app: nodejs
  name: nodejs
spec:
  backend:
    serviceName: nodejs-backend
    servicePort: 8080

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: nodejs-backend
  labels:
    app: nodejs
spec:
  type: NodePort
  selector:
    app: nodejs
  ports:
  - port: 8080
    targetPort: 8080
