apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nodejs
spec:
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: "gcr.io/zuru-tech-hiring/nodejs:latest"
        imagePullPolicy: Always
        resources:
          requests:
            memory: 100Mi
            cpu: 50m
          limits:
            memory: 1536Mi
            cpu: 55m
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: nodejs-backend
  labels:
    app: nodejs
spec:
  type: NodePort
  selector:
    app: nodejs
  ports:
    - port: 8080