apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nodejs-hpa
spec:
  maxReplicas: 8
  minReplicas: 3
  scaleTargetRef:
    apiVersion: extensions/v1
    kind: Deployment
    name: nodejs
  targetCPUUtilizationPercentage: 75
