apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: nodejs
  name: nodejs
spec:
  backend:
    serviceName: nodejs-backend
    servicePort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: nodejs-backend
  labels:
    app: nodejs
spec:
  type: NodePort
  selector:
    app: nodejs
  ports:
  - port: 8080
    targetPort: 8080