apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nodejs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: "gcr.io/zuru-tech-hiring/nodejs:latest"
        imagePullPolicy: Always
        resources:
          requests:
            memory: 100Mi
            cpu: 50m
          limits:
            memory: 1536Mi
            cpu: 55m
        ports:
        - containerPort: 8080

---

apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: nodejs-domain-certificate
spec:
  domains:
    - mytestwebsite.tk

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.global-static-ip-name: nodejs-static-ip
    networking.gke.io/managed-certificates: nodejs-domain-certificate
  labels:
    app: nodejs
  name: nodejs
spec:
  backend:
    serviceName: nodejs-backend
    servicePort: 8080

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: nodejs-backend
  labels:
    app: nodejs
spec:
  type: NodePort
  selector:
    app: nodejs
  ports:
  - port: 8080
    targetPort: 8080
